// home
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const SUBMIT_FORM_LOADING = 'SUBMIT_FORM_LOADING';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR';
